add_newline = false

format = """
󰌽 \
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$fill\
$time\n$character
"""

[fill]
symbol = ' '

[directory]
style = "purple"
format = "[$path ]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Desktop" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[username]
show_always = true
style_user = "bold"
style_root = "bold red"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
format = '@[$hostname]($style):$ssh_symbol'
ssh_symbol = "󰄙 "
style = "bold green"
disabled = false

[git_branch]
symbol = ""
style = "cyan"
format = '[\[ $symbol $branch ]($style)'

[git_status]
style = "cyan"
format = '[($all_status$ahead_behind )\]]($style)'

[nodejs]
symbol = ""
style = ""
format = '[\[ $symbol ($version) \]]($style)'

[rust]
symbol = ""
style = ""
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = ""
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = ""
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "reverse"
format = '[$fill $time]($style)'

