name: Hardware Enablement
description: File a report for the hardware you would like enabled to Serpent OS. 
title: "[Hardware Enablement Report]: "
labels: ["hardware"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this hardware report! Your interest in Serpent OS is appreciated and we hope to better support your hardware in time.
  - type: checkboxes
    id: search
    attributes:
      label: Existing reports?
      description: Before opening a new issue, please search [the open issues](https://github.com/serpent-os/recipes/issues?q=is%3Aopen+is%3Aissue) to ensure there is not already an open hardware enablement report for the problem.
      options:
        - label: I have searched open hardware enablement reports for this issue
          required: true
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      options:
        - label: Is system up to date?
  - type: dropdown
    id: desktop_environment
    attributes:
      label: Desktop Environment
      options:
        - GNOME
        - Cosmic
        - Sway
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What hardware is not working?
      description: Please explain what hardware did not work. Whether the whole computer did not work or specific pieces of hardware (eg. wifi or webcame etc_
      placeholder: Tell us what you see!
      value: "Please fill in the details here!"
    validations:
      required: true
  - type: textarea
    id: logs-lspci-good
    attributes:
      label: lspci output from known good distro 
      description: Please copy and paste the output of 'sudo lspci -vnn' from a known good distro. It is helpful to understand which drivers are in use. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs-lspci-serpent
    attributes:
      label: lspci output from Serpent OS 
      description: Please copy and paste the output of 'sudo lspci -vnn' from Serpent OS. If the command does not work, install using 'sudo moss install pciutils'. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs-lsusb
    attributes:
      label: lsusb output from within Serpent OS
      description: Please copy and paste the output of 'sudo lsusb' from Serpent OS. If the command does not work, install using 'sudo moss install usbutils'. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs-dmidecode
    attributes:
      label: dmidecode output from within Serpent OS
      description: Please copy and paste the output of 'sudo dmidecode' from Serpent OS. If the command does not work, install using 'sudo moss install dmidecode'. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: System details
      description: Provide the output of 'inxi -b' from command line. If the command does not work, install using 'sudo moss install inxi'.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other comments
      description: Any other details that might help diagnose the issue
